### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Mullayam** [uixmat/onborda#10]
copied the code then also not

![image](https://github.com/uixmat/onborda/assets/50077856/b29aa9c4-9c82-4d8a-8e64-b898c2a09a23)

**Comment by uixmat** [comment]
First of all your `OnbordaProvider` should be at the highest level in the DOM tree and therefore your `TooltipProvider` should preferrably be nested inside `<Onborda />` compopnent.

In future try to provide as much information as possible when reporting a problem and either myself or a community member will try to help you!
