### ISSUE TITLE
Listen to element resize, not just window resize.

### ISSUE THREAD

**Issue by JoshuaKirby88** [uixmat/onborda#16]
Currently, the Onborda component listens to window resizing via this useEffect:
```
  useEffect(() => {
    if (isOnbordaVisible) {
      window.addEventListener("resize", updatePointerPosition);
      return () => window.removeEventListener("resize", updatePointerPosition);
    }
  }, [currentStep, currentTourSteps, isOnbordaVisible]);
```

I suggest also listening to element resizing for 2 reasons:
1. When the highlighted element resizes, the pointerPosition should also update, rather than staying in place.
2. Listening to a parent of the highlighted element's resize events can effectively track the position of the highlighted element when the highlighted element isn't resizing, but only the position is changing.

Caveats:
When the highlighted element's position is changing, but the parent container isn't resizing, this will not be able to track the position of the highlighted element.

This is what I have currently implemented in my forked Onborda component:

- I am using 2 hooks from "usehooks-ts".
- To useResizeObserver, I am passing in either the element using a custom column called "observeResizeSelector" which if provided, will not listen to the resizing of the highlighted element, but a separate element.
- Using .slice(1) to get rid of "#".
- Calling getElementPosition whenever the element resizes, and setting the returned value to setPointerPosition.

```
import { useIsMounted, useResizeObserver } from "usehooks-ts"
    const isMounted = useIsMounted()
    // Calculate position on element resize
    useResizeObserver({
        ref: { current: isMounted() ? document.getElementById(currentTourSteps[currentStep]?.observeResizeSelector.slice(1) ?? currentTourSteps[currentStep]?.selector.slice(1)) : null },
        onResize: () => setPointerPosition(getElementPosition(document.querySelector(currentTourSteps[currentStep]?.selector)))
    })
```

**Comment by uixmat** [comment]
@JoshuaKirby88 thanks for the feedback, onborda already resizes according to the target element! See video below from the [onborda.dev](https://onborda.dev) homepage.

https://github.com/user-attachments/assets/cc733940-59ad-415a-9e61-76484769e1a2

**Comment by JoshuaKirby88** [comment]
Perfect! Thanks.
