### ISSUE TITLE
Overlay clickthrough

### ISSUE THREAD

**Issue by foureight84** [uixmat/onborda#18]
I'm currently using v1.2.4 and it's working beautifully on Nextjs14 with tailwindcss. The one thing I noticed is that the link, and other elements beneath the overlay are still clickable. An accidental click during a tour would send the user to a different route while the tour's context remains the same.

**Comment by uixmat** [comment]
This will be added to the roadmap to disallow clickthrough's

**Comment by raviriley** [comment]
Onborda is kinda useless without this, big + 1

**Comment by yousefelgoharyx** [comment]
UMMMMM
I actually need the option to allow clicking through xD

**Comment by yousefelgoharyx** [comment]
Here's a quick fix if any encountered this issue
```css
[data-name='onborda-overlay'] {
  pointer-events: none !important;
}
```

**Comment by fikricanozgur** [comment]
> Here's a quick fix if any encountered this issue
> 
> ```css
> [data-name='onborda-overlay'] {
>   pointer-events: none !important;
> }
> ```

Where exactly did you use data-name="onborda-overlay" to disallow clickthrough's?

**Comment by uixmat** [comment]
Going to push an update for this this week guys. Will add a prop to the parent component to disable/enable click through ✌️

**Comment by fikricanozgur** [comment]
any updates?

**Comment by mikhael28** [comment]
@uixmat no rush man! It's open-source software, get to it when you get to it - or don't! I appreciate this library so much, thank you for your work. If the software development world had the equivalent of a 'Emmy' or 'Oscar' award, this should be nominated for 'Best Costume' or something like that. It's such a neatly designed, compact tour library - it does exactly what someone writing common sense software would want. Cheers, you are awesome.

**Comment by uixmat** [comment]
Apologies all for the long wait for this feature! In version 1.2.5 (just released), `Onborda` component now accepts an optional `boolean` prop: `interact` (defaulted to false). 

Ref: https://github.com/uixmat/onborda/blob/main/src/Onborda.tsx#L13

This prevents interacting (by default) with anything on the page that isn't the step target or the step card.
