### ISSUE TITLE
Making target element functional / clickable

### ISSUE THREAD

**Issue by enszrlu** [uixmat/onborda#22]
Is there a way of making target still accessible? 

For example if on boarding goes thru a form and I want users to fill out form one by one, I am not able to do it at the moment. 
I could not find anything regarding this in docs.

**Comment by nyamkamunhjin** [comment]
Have you found any workaround for this? I'm blocked with a same problem currently

**Comment by uixmat** [comment]
@enszrlu @nyamkamunhjin can you both provide more context to the problem your having, a screen recording would be super helpful!

**Comment by enszrlu** [comment]
> Have you found any workaround for this? I'm blocked with a same problem currently

I had bunch of other requirements for my project so I released another package referencing to Onborda. [nextstepjs.com](https://nextstepjs.com)

**Comment by enszrlu** [comment]
> @enszrlu @nyamkamunhjin can you both provide more context to the problem your having, a screen recording would be super helpful!

Hi mate, when you target an area with selector; it does not allow you to interact with it. For example, if you target an input box, you cannot enter any values as you cannot click into the box. 

Is it more clear? 

Thanks for great work ❤️

**Comment by uixmat** [comment]
Ah great work man! Yea much clearer, will do some additional work on this tonight 🫡

**Comment by uixmat** [comment]
@enszrlu fixed in [v.1.2.5](https://github.com/uixmat/onborda/releases/tag/v.1.2.5)
