### ISSUE TITLE
Multiple Onboarding/ Sections?

### ISSUE THREAD

**Issue by imesse** [uixmat/onborda#3]
I think the idea is very nice! :clap:
It would be cool to have the possibility to use multiple types of onboarding, for example by dividing them into sections. 
If you think it is a feature worth adding I am willing to contribute to the repo.

**Comment by uixmat** [comment]
I'm current working on a version2 that will have multiple onboarding flows and a tour bar to allow you to navigate between steps 💪🏼

**Comment by imesse** [comment]
Great! It would also be nice if we could improve the mobile responsiveness, by editing the CustomCard I managed to get out of it but I am not fully satisfied with the result I got, maybe adding some positions would help, like (top-left, topRight, bottomLeft and bottomRight) what do you think?
Again I volunteer as a contributor to the repo! Let me know if I can be of any help to you!

**Comment by flawnson** [comment]
Same here! Would love to be able to do multiple onboarding sections. Mainly I'd like to be able to create seperate tours for desktop and mobile versions of the app.

Also keen to help as a contributor!

**Comment by uixmat** [comment]
This is now available in version 1.2.3 (released today)!
