### ISSUE TITLE
Provide documentation for onboarda adopters

### ISSUE THREAD

**Issue by buzzie-bee** [uixmat/onborda#7]
I've been researching possible packages to use for some tours I want to build into my nextjs app using shadcn/ui, tailwind, and framer motion. 

This project looks like it could be a perfect fit! However there doesn't seem to be any documentation into it yet.

It looks like it's a pretty new project, so it's probably just on the roadmap for the future, but without documentation it's difficult to justify adopting the lib. I saw a comment that a v2 is being worked on, so I figured opening this ticket would help track the request for documentation so it can possibly be included with that v2.

I think there's a really strong case for a more 'headless' tour package which lets users implement their own components and styling and/or uses some prebuilt copy paste shadcn style components so I'm looking forward to seeing where this project goes :)

**Comment by uixmat** [comment]
It's coming for the next version @buzzie-bee !

**Comment by uixmat** [comment]
@buzzie-bee the new [onborda website](https://onborda.dev) has some [basic docs](https://onborda.dev/docs) to help users get started!
